plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.conversantmedia:disruptor:1.2.10'
    implementation files('lib/ojdbc14.jar')
}

tasks.register('copyProperties', Copy) {
    from('src/main/java') {
        include '**/*.properties'
    }
    into 'build/classes/java/main'
}

shadowJar {
    dependsOn copyProperties
    mergeServiceFiles()
    archiveBaseName = 'orauld'
    archiveClassifier = ''

    // 显式包含ojdbc jar文件
    from zipTree('lib/ojdbc14.jar')
}

jar {
    dependsOn copyProperties
    manifest {
        attributes 'Main-Class': 'github.peihanw.orauld.OrauldMain'
    }
}

build.dependsOn copyProperties
build.dependsOn shadowJar