plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

// 添加项目的基本信息
group = 'github.peihanw'
version = '1.0.0' // 根据需要调整版本号
// artifactId 默认使用项目目录名，也可以显式指定（见下方说明）

sourceCompatibility = 1.7
targetCompatibility = 1.7

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'com.conversantmedia', name: 'disruptor', version: '1.2.10', classifier: 'jdk7'
    implementation files('lib/ojdbc14.jar')
    implementation 'joda-time:joda-time:2.10.10'
}

tasks.register('copyProperties', Copy) {
    from('src/main/java') {
        include '**/*.properties'
    }
    into 'build/classes/java/main'
}

shadowJar {
    dependsOn copyProperties
    mergeServiceFiles()
    archiveBaseName = 'orauld'
    archiveClassifier = ''

    // 显式包含ojdbc jar文件
    from zipTree('lib/ojdbc14.jar')
}

jar {
    dependsOn copyProperties
    manifest {
        attributes 'Main-Class': 'github.peihanw.orauld.OrauldMain'
    }
}

// 显式指定 artifactId（而不是使用默认的目录名）
base {
    archivesName = 'orauld'
}

build.dependsOn copyProperties
build.dependsOn shadowJar